/*
 * gfxforge-web — FULL BATTERY TEST (movie generator)
 * ==================================================
 * Emits `battery.gfx`, a single movie that exercises *every* capability of the
 * gfxforge-web codec, so it can be injected into Mercenaries 2 and visually
 * checked feature-by-feature. Paired with `battery_test.lua`, which loads and
 * drives it in-game.
 *
 * WHY THIS EXISTS: the core encoders (solid rects, text, buttons, menus, basic
 * AVM1) are byte-identical to the in-game-proven Python `gfxforge`. The *newer*
 * surface — rounded corners, strokes, gradients, embedded bitmaps, and the
 * extended compiler (for / arrays / break / continue) — has no independent
 * reference and is flagged lower-confidence in the README. This panel puts all
 * of it on screen at once so we can confirm what actually renders in GFx 2.x.
 *
 * RUN:  node examples/mercs2/battery_test.js        # -> examples/mercs2/battery.gfx
 *
 * The codec is browser-style (IIFE + globals), so we load it through the repo's
 * node harness (tests/run.js `loadContext`) exactly as the test-suite does.
 *
 * CONTRACT shared with battery_test.lua:
 *   asset      : battery                      (host: SetSwfFile "battery.gfx")
 *   vars       : hp_val sel_val calc_val list_val ; menu index _root.i (n = 4)
 *   functions  : SetHealth(n) SetSync(p) Move(d) Choose() Diagnostics()
 *                SetSelected(i)              (generated by menu())
 *   clips      : bar (SYNC gauge, scaled via _xscale)  sel (menu highlight)
 *   events out : warn (health < 25) ; choose (index) ; diag (checksum)
 */
'use strict';
const fs = require('fs');
const path = require('path');

// --- load the codec into node (same mechanism the tests use) ----------------
const { loadContext } = require(path.join(__dirname, '..', '..', 'tests', 'run.js'));
const ctx = loadContext();
const { Movie } = ctx.GFMovie;
const Compiler = ctx.Compiler;

// --- palette ---------------------------------------------------------------
const AMBER = [255, 196, 72], LIGHT = [228, 232, 236], DARK = [25, 25, 25];
const GREY = [150, 160, 172], TEAL = [46, 200, 208], PURPLE = [150, 110, 220];
const CYAN = [90, 210, 255], GREEN = [90, 200, 120], TRACK = [44, 48, 54];

// A small checkerboard raster (obviously a bitmap, not a vector gradient), so
// the BITMAP swatch is unmistakable if it renders. imageData is {width,height,
// data:RGBA} — the same shape a browser canvas ImageData has.
function checker(w, h, cell, c1, c2) {
  const data = new Uint8Array(w * h * 4);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const on = (Math.floor(x / cell) + Math.floor(y / cell)) % 2 === 0;
      const c = on ? c1 : c2;
      const i = (y * w + x) * 4;
      data[i] = c[0]; data[i + 1] = c[1]; data[i + 2] = c[2]; data[i + 3] = 255;
    }
  }
  return { width: w, height: h, data };
}

const m = new Movie(520, 400, { name: 'battery', background: [18, 20, 24] });

// header ---------------------------------------------------------------------
m.rect(0, 0, 520, 30, AMBER);
m.text(12, 7, 'GFXFORGE-WEB BATTERY TEST', { size: 14, color: DARK });

// helper: a labelled 100x36 swatch at (col,row) --------------------------------
function swatch(x, y, label, fill, opts) {
  m.text(x, y - 14, label, { size: 11, color: GREY, width: 116 });
  m.rect(x, y, 100, 36, fill, opts || {});
}

// column 1 — fill/shape variants (the "new" vector surface) ------------------
swatch(12, 54, 'SOLID', TEAL);
swatch(12, 110, 'ROUNDED r14', PURPLE, { radius: 14 });
swatch(12, 166, 'STROKE 3px', [30, 34, 40], { stroke: { width: 3, color: CYAN } });

// column 2 — gradients (lowest-confidence: matrix math has no reference) ------
swatch(130, 54, 'GRAD linear V', { type: 'linear', direction: 'vertical',
  stops: [{ ratio: 0, color: AMBER }, { ratio: 255, color: [200, 60, 40] }] });
swatch(130, 110, 'GRAD linear H', { type: 'linear', direction: 'horizontal',
  stops: [{ ratio: 0, color: [40, 90, 200] }, { ratio: 255, color: CYAN }] });
swatch(130, 166, 'GRAD radial', { type: 'radial', direction: 'vertical',
  stops: [{ ratio: 0, color: [240, 240, 250] }, { ratio: 255, color: [30, 40, 80] }] });

// column 3 — combined + bitmap -----------------------------------------------
swatch(248, 54, 'ROUND+GRAD+STROKE',
  { type: 'linear', direction: 'vertical', stops: [{ ratio: 0, color: GREEN }, { ratio: 255, color: [30, 110, 60] }] },
  { radius: 10, stroke: { width: 2, color: LIGHT } });
m.text(248, 96, 'BITMAP (checker)', { size: 11, color: GREY, width: 116 });
m.image(248, 110, 100, 36, checker(20, 12, 3, [255, 120, 40], [40, 44, 60]));

// dynamic readouts (variable-bound text, driven from AS2/Lua) ----------------
function readout(x, y, label, varName, color) {
  m.text(x, y, label, { size: 12, color: LIGHT, width: 70 });
  m.text(x + 74, y, '--', { size: 12, color: color, varName: varName, width: 170 });
}
readout(248, 156, 'HEALTH', 'hp_val', AMBER);
readout(12, 224, 'SELECT', 'sel_val', CYAN);
readout(12, 246, 'CALC',   'calc_val', GREEN);   // from the for/break/continue loop
readout(12, 268, 'LIST',   'list_val', LIGHT);   // from the while loop + array join

// SYNC gauge — a named clip the AVM1 SetSync scales via _xscale ---------------
m.text(12, 300, 'SYNC', { size: 12, color: GREY });
m.rect(12, 318, 320, 14, TRACK);
m.clip('bar', 12, 318, 316, 14, GREEN);

// selectable menu (buttons + movable highlight + generated SetSelected) ------
m.menu(400, 54, ['RESUPPLY', 'AIRSTRIKE', 'EVAC', 'ABORT'],
  { width: 108, rowH: 22, textColor: LIGHT });

m.text(12, 360, 'up/dn move   enter choose   (driven from Lua key-watch)', { size: 11, color: GREY, width: 500 });

// behaviour — one AS2 program compiled to AVM1. Exercises the whole compiler:
// functions, if, while, FOR, ARRAYS + indexing, BREAK/CONTINUE, string concat,
// member access, fscommand, arithmetic + comparisons.
m.script(Compiler.compileSource(`
  _root.hp_val = "100";
  _root.n = 4;
  _root.i = 0;
  _root.opts = ["RESUPPLY", "AIRSTRIKE", "EVAC", "ABORT"];

  function SetHealth(n) {
    _root.hp_val = n;
    if (n < 25) { fscommand("warn", n); }
  }

  function SetSync(p) { _root.bar._xscale = p; }

  function Move(d) {
    _root.i = _root.i + d;
    if (_root.i < 0)           { _root.i = _root.n - 1; }
    if (_root.i > _root.n - 1) { _root.i = 0; }
    SetSelected(_root.i);
    _root.sel_val = _root.opts[_root.i];
  }

  function Choose() { fscommand("choose", _root.i); }

  function Diagnostics() {
    var sum = 0;
    var vals = [3, 1, 4, 1, 5, 9, 2, 6];
    var k = 0;
    for (k = 0; k < 8; k = k + 1) {
      if (vals[k] == 1) { continue; }   // skip 1s
      if (vals[k] > 6)  { break; }       // stop at the 9
      sum = sum + vals[k];               // 3 + 4 + 5 = 12
    }
    _root.calc_val = sum;

    var s = "";
    var j = 0;
    while (j < _root.n) {
      s = s + _root.opts[j];
      if (j < _root.n - 1) { s = s + " / "; }
      j = j + 1;
    }
    _root.list_val = s;

    fscommand("diag", sum);
  }
`));

const out = path.join(__dirname, 'battery.gfx');
fs.writeFileSync(out, Buffer.from(m.build()));
console.log('wrote ' + out + ' (' + fs.statSync(out).size + ' bytes)');
